tools:
  jdk: 8
  maven: 3.6.2
  
envs:
  prod:
    variables:
      env: prod
       
  stage:
    variables:
      env: stage
       
triggers:
  - manual: Run default
  
  - manual: 
      name: prod Smoke Test
      call: prod_smoke_test
     
  - manual: 
      name: prod Regression Test
      call: prod_regression_test   
     
  - manual: 
      name: Stage Smoke Test
      call: stage_smoke_test
     
  - manual: 
      name: Stage Regression Test
      call: stage_regression_test     
    
flows: 
  default:
    - node(windows):
      - call: smoke_test(stage)
  
  prod_smoke_test:
    - call: smoke_test(prod)
    
  stage_smoke_test:
    - call: smoke_test(stage)    
 
  prod_regression_test:
    - call: regression_test(prod)  
    
  stage_regression_test:
    - call: regression_test(stage)  
    
  
  smoke_test:
    try: 
      - echo "Started smoke test on ${env} environment."   
      - mvn test -Denv=${env} -Dcucumber.options="--tags @smoke"
      - publishReport:
          context: cucumber
          dir: target
          index: DbValidationsTest.html
          verbose: true
      - mail:
          from: sams-automation@walmart.com
          to: abubakkar.farooque@walmart.com
          contentType: text/html
          subject: "Promotions automation report"
          messageFromFile: "target/DbValidationsTest.html"
          
      - try:
           - slack.postMessage:
               message: "ReverseSync and ForwardSync build status: SUCCESS!"
               channelId: "promotions-test"
               iconEmoji: ":coolstorydp:"
               username: "Promotions Automation Bot"
               attachments:
                  - fallback: ${BUILD_URL}
                    actions:
                    - type: "button"
                      text: "Build info and log"
                      url: ${BUILD_URL}
        catch:
           - slack.postMessage:
                message: "ReverseSync and ForwardSync build status: FAIL"
                channelId: "promotions-test"
                iconEmoji: ":sadpanda:"
                username: "Promotions Automation Bot"
                attachments:
                  - fallback: ${BUILD_URL}
                    actions:
                    - type: "button"
                      text: "Build info and log"
                      url: ${BUILD_URL}
    catch:
      - try:
           - slack.postMessage:
               message: "ReverseSync and ForwardSync Build failed"
               channelId: "promotions-test"
               iconEmoji: ":sadpanda:"
               username: "Promotions Automation Bot"
           - publishReport:
               context: cucumber
               dir: target
               index: DbValidationsTest.html
               verbose: true
           - mail:
               from: sams-automation@walmart.com
               to: abubakkar.farooque@walmart.com
               contentType: text/html
               subject: "Promotions automation report"
               messageFromFile: "target/DbValidationsTest.html"   
        catch:
          - echo "Something happened wrong" 
      - exit 1      
    
  regression_test:
    try: 
      - echo "Started regression test on ${env} environment."   
      - mvn test -Denv=${env} -Dcucumber.options="--tags @regressionBroadReach"
      - publishReport:
          context: cucumber
          dir: target
          index: ExtentReportBroadReachTest.html
          verbose: true
      - mail:
          from: sams-automation@walmart.com
          to: abubakkar.farooque@walmart.com
          contentType: text/html
          subject: "Promotions automation report"
          messageFromFile: "target/ExtentReportBroadReachTest.html"
          
      - try:
           - slack.postMessage:
               message: "BroadReach Promotions Validation build status: SUCCESS!"
               channelId: "promotions-test"
               iconEmoji: ":coolstorydp:"
               username: "Promotions Automation Bot"
               attachments:
                  - fallback: ${BUILD_URL}
                    actions:
                    - type: "button"
                      text: "Build info and log"
                      url: ${BUILD_URL}
        catch:
           - slack.postMessage:
                message: "BroadReach Promotions Validation build status: FAIL"
                channelId: "promotions-test"
                iconEmoji: ":sadpanda:"
                username: "Promotions Automation Bot"
                attachments:
                  - fallback: ${BUILD_URL}
                    actions:
                    - type: "button"
                      text: "Build info and log"
                      url: ${BUILD_URL}
    catch:
      - try:
           - slack.postMessage:
               message: "BroadReach Promotions Build Failed"
               channelId: "promotions-test"
               iconEmoji: ":sadpanda:"
               username: "Promotions Automation Bot"
           - publishReport:
               context: cucumber
               dir: target
               index: ExtentReportBroadReachTest.html
               verbose: true
           - mail:
               from: sams-automation@walmart.com
               to: abubakkar.farooque@walmart.com
               contentType: text/html
               subject: "Promotions automation report"
               messageFromFile: "target/ExtentReportBroadReachTest.html"   
        catch:
          - echo "Something happened wrong"                   
      - exit 1     
    
