tools:
  jdk: 8
  maven: 3.6.2
  
envs:
  prod:
    variables:
      env: prod
       
  stage:
    variables:
      env: stage
       
triggers:
  - manual: Run default
  
  - manual: 
      name: prod Smoke Test
      call: prod_smoke_test
     
  - manual: 
      name: prod Regression Test
      call: prod_regression_test   
     
  - manual: 
      name: Stage Smoke Test
      call: stage_smoke_test
     
  - manual: 
      name: Stage Regression Test
      call: stage_regression_test     
    
flows: 
  default:
    - node(windows):
      - call: smoke_test(stage)
    
  prod_smoke_test:
    - call: smoke_test(prod)
    
  stage_smoke_test:
    - call: smoke_test(stage)    
 
  prod_regression_test:
    - call: regression_test(prod)  
    
  stage_regression_test:
    - call: regression_test(stage)  
    
  
  smoke_test:
    try: 
      - echo "Started smoke test on ${env} environment."   
      - mvn test -Denv=${env} -Dcucumber.options="--tags @smoke"
      - publishReport:
         context: cucumber
         dir: reports
         index: Smoke-report.html
         verbose: true
      - mail:
          from: sams-automation@walmart.com
          to: Abubakkar.Farooque@walmart.com
          contentType: text/html
          subject: "Promotions automation report:"
          messageFromFile: "reports/report.html"
          
      - try:
           - slack.postMessage:
               message: "ReverseSync and ForwardSync build status: SUCCESS!"
               channelId: "qe-walmart"
               iconEmoji: ":coolstorydp:"
               username: "Promotions Automation Bot"
               attachments:
                  - fallback: ${BUILD_URL}
                    actions:
                    - type: "button"
                      text: "Build info and log"
                      url: ${BUILD_URL}
        catch:
           - slack.postMessage:
                message: "ReverseSync and ForwardSync build status: FAIL"
                channelId: "qe-walmart"
                iconEmoji: ":sadpanda:"
                username: "Promotions Automation Bot"
                attachments:
                  - fallback: ${BUILD_URL}
                    actions:
                    - type: "button"
                      text: "Build info and log"
                      url: ${BUILD_URL}
    catch:
      - echo "Something happened wrong"
      - exit 1      
    
  regression_test:
    try: 
      - echo "Started regression test on ${env} environment."   
      - mvn test -Denv=${env} -Dcucumber.options="--tags @regressionBroadReach"
      - mail:
          from: sams-automation@walmart.com
          to: Abubakkar.Farooque@walmart.com
          contentType: text/html
          subject: "Promotions automation report:"
          messageFromFile: "reports/report.html"
    catch:
      - echo "Something happened wrong"
      - exit 1     
    
