Feature: Update Value Coupon , Value Coupon Store and Value Coupon Items Table in DB2

  Scenario Outline: Update Tables
    Given Values to Update value coupon Table
      | VALUE_COUPON_NBR   | BASE_DIV_NBR   | START_DATE   | END_DATE   | START_TIME   | END_TIME   | ACTIVE_IND   | COUPON_ITEM_NBR   | COUPON_UPC_NBR   | VALUE_AMT   | VALUE_PCT   | PACKAGE_CODE   | INVESTMENT_AMT   | INVESTMENT_CNT   | DURATION_CODE   | VENDOR_FUNDED_IND   | SHARED_VALUE_IND   | PRVDR_COUPON_NBR   | MANUAL_LOAD_IND   | VAL_OFFER_TYP_CODE   | MAX_RDMPT_CNT   | MIN_BASKET_AMT   | VAL_ASSIGN_TYPE_CD   | LAST_CHANGE_DATE   | LAST_CHG_PGM_ID   | CAMPAIGN_NBR   | PURCH_FREQUENCY_PCT   | FUNDING_TYPE_CD   | SUMMARY_DESC   | DETAIL_DESC   | RETAIL_AFTER_DISC_IND   | MAX_PURCHASE_AMT   | MAX_PURCHASE_QTY   | MAX_DISC_AMT   | MIN_CORE_PURCH_QTY   | MIN_SEED_PURCH_QTY   | MIN_REWARD_PURCH_QTY   | OFFER_AVAIL_DELAY_DAY_CNT   | OFFER_DUR_DELAY_DAY_CNT   | ASSGN_INVST_CNT   | REDEMPTION_INVST_CNT   |
      | <VALUE_COUPON_NBR> | <BASE_DIV_NBR> | <START_DATE> | <END_DATE> | <START_TIME> | <END_TIME> | <ACTIVE_IND> | <COUPON_ITEM_NBR> | <COUPON_UPC_NBR> | <VALUE_AMT> | <VALUE_PCT> | <PACKAGE_CODE> | <INVESTMENT_AMT> | <INVESTMENT_CNT> | <DURATION_CODE> | <VENDOR_FUNDED_IND> | <SHARED_VALUE_IND> | <PRVDR_COUPON_NBR> | <MANUAL_LOAD_IND> | <VAL_OFFER_TYP_CODE> | <MAX_RDMPT_CNT> | <MIN_BASKET_AMT> | <VAL_ASSIGN_TYPE_CD> | <LAST_CHANGE_DATE> | <LAST_CHG_PGM_ID> | <CAMPAIGN_NBR> | <PURCH_FREQUENCY_PCT> | <FUNDING_TYPE_CD> | <SUMMARY_DESC> | <DETAIL_DESC> | <RETAIL_AFTER_DISC_IND> | <MAX_PURCHASE_AMT> | <MAX_PURCHASE_QTY> | <MAX_DISC_AMT> | <MIN_CORE_PURCH_QTY> | <MIN_SEED_PURCH_QTY> | <MIN_REWARD_PURCH_QTY> | <OFFER_AVAIL_DELAY_DAY_CNT> | <OFFER_DUR_DELAY_DAY_CNT> | <ASSGN_INVST_CNT> | <REDEMPTION_INVST_CNT> |
    Then Values to Update value coupon Items
      | VALUE_COUPON_NBR   | ITEM_NBR   | VAL_ITEM_TYPE_CODE   | DEPT_NBR   | SUBCLASS_NBR   | VENDOR_NBR   | MIN_ITEM_PURCH_QTY   |
      | <VALUE_COUPON_NBR> | <ITEM_NBR> | <VAL_ITEM_TYPE_CODE> | <DEPT_NBR> | <SUBCLASS_NBR> | <VENDOR_NBR> | <MIN_ITEM_PURCH_QTY> |
    Then Values to Update value coupon Store
      | VALUE_COUPON_NBR   | STORE_NBR   | START_DATE   | END_DATE   | START_TIME   | END_TIME   |
      | <VALUE_COUPON_NBR> | <STORE_NBR> | <START_DATE> | <END_DATE> | <START_TIME> | <END_TIME> |

    Examples: 
      | VALUE_COUPON_NBR | BASE_DIV_NBR | START_DATE | END_DATE   | START_TIME | END_TIME | ACTIVE_IND | COUPON_ITEM_NBR | COUPON_UPC_NBR | VALUE_AMT | VALUE_PCT | PACKAGE_CODE | INVESTMENT_AMT | INVESTMENT_CNT | DURATION_CODE | VENDOR_FUNDED_IND | SHARED_VALUE_IND | PRVDR_COUPON_NBR | MANUAL_LOAD_IND | VAL_OFFER_TYP_CODE | MAX_RDMPT_CNT | MIN_BASKET_AMT | VAL_ASSIGN_TYPE_CD | LAST_CHANGE_DATE | LAST_CHG_PGM_ID | CAMPAIGN_NBR | PURCH_FREQUENCY_PCT | FUNDING_TYPE_CD | SUMMARY_DESC         | DETAIL_DESC                  | RETAIL_AFTER_DISC_IND | MAX_PURCHASE_AMT | MAX_PURCHASE_QTY | MAX_DISC_AMT | MIN_CORE_PURCH_QTY | MIN_SEED_PURCH_QTY | MIN_REWARD_PURCH_QTY | OFFER_AVAIL_DELAY_DAY_CNT | OFFER_DUR_DELAY_DAY_CNT | ASSGN_INVST_CNT | REDEMPTION_INVST_CNT | ITEM_NBR    | VAL_ITEM_TYPE_CODE | DEPT_NBR | SUBCLASS_NBR | VENDOR_NBR | MIN_ITEM_PURCH_QTY | STORE_NBR |
      |            77465 |           18 | 2020-02-13 | 2022-08-08 | 00:00:00   | 23:59:00 | A          |       280253432 |    40980209741 |        2  |         0 |           96 |              0 |              0 |             0 | N                 | Y                |                0 | Y               |                 22 |         9999  |              0 |                  4 | 2019-01-25       | RVSYNC          |         1651 |                   0 |               1 | IS M&M $Dis          | IS Test                      |                     0 |                0 |                0 |            0 |                  1 |                  0 |                    0 |                         0 |                       0 |               0 |                    0 |   120324    |                  1 |        0 |            0 |          0 |                  1 |      6279 |
			|            73293 |           18 | 2020-02-13 | 2022-08-08 | 00:00:00   | 23:59:00 | A          |       280253402 |    40980209741 |        2  |         0 |           96 |              0 |              0 |             0 | N                 | Y                |                0 | Y               |                 22 |         9999  |              0 |                  4 | 2019-01-25       | RVSYNC          |         1651 |                   0 |               1 | IS M&M $Dis          | IS Test2                     |                     0 |                0 |                0 |            0 |                  1 |                  0 |                    0 |                         0 |                       0 |               0 |                    0 |   151806    |                  1 |        0 |            0 |          0 |                  1 |      6279 |
			|            73291 |           18 | 2020-02-13 | 2022-08-08 | 00:00:00   | 23:59:00 | A          |      2802534812 |    40980209741 |        0  |         25|           96 |              0 |              0 |             0 | N                 | Y                |                0 | Y               |                 22 |         9999  |              0 |                  4 | 2019-01-25       | RVSYNC          |         1651 |                   0 |               1 | IS M&M $Dis          | IS Test3                     |                     0 |                0 |                0 |            0 |                  1 |                  0 |                    0 |                         0 |                       0 |               0 |                    0 |   428484    |                  1 |        0 |            0 |          0 |                  1 |      6279 |
			|            73592 |           18 | 2020-02-13 | 2022-08-08 | 00:00:00   | 23:59:00 | A          |      280253422  |    40980209741 |        0  |         5 |           96 |              0 |              0 |             0 | N                 | Y                |                0 | Y               |                 22 |         10    |              0 |                  4 | 2019-01-25       | RVSYNC          |         1651 |                   0 |               1 | IS M&M $Dis          | IS Test4                     |                     0 |                0 |                0 |            0 |                  1 |                  0 |                    0 |                         0 |                       0 |               0 |                    0 |   644660    |                  1 |        0 |            0 |          0 |                  1 |      6279 |
			|            77999 |           18 | 2020-02-13 | 2022-08-08 | 00:00:00   | 23:59:00 | A          |      280253432  |    40980209741 |      0.5  |         0 |           96 |              0 |              0 |             0 | N                 | Y                |                0 | Y               |                 22 |       9999    |              0 |                  4 | 2019-01-25       | RVSYNC          |         1651 |                   0 |               1 | IS M&M $Dis          | IS Test5                     |                     0 |                0 |                0 |            0 |                  1 |                  0 |                    0 |                         0 |                       0 |               0 |                    0 |980181469    |                  1 |        0 |            0 |          0 |                  1 |      6279 |
			